
FROM public.ecr.aws/lambda/python:latest

WORKDIR ${LAMBDA_TASK_ROOT}

RUN dnf update -y \
    && dnf clean all \
    && dnf install -y tar gzip bzip2
RUN dnf install xz atk cups-libs gtk3 libXcomposite alsa-lib \
    libXcursor libXdamage libXext libXi libXrandr libXScrnSaver \
    libXtst pango at-spi2-atk libXt xorg-x11-server-Xvfb \
    xorg-x11-xauth dbus-glib dbus-glib-devel -y

RUN rm -rf /var/cache/dnf

COPY install-firefox.sh .

RUN bash install-firefox.sh

COPY requirements.txt  .

RUN  pip3 install -r requirements.txt

COPY steam_extract.py .

CMD [ "steam_extract.handler" ]